#!/bin/bash

# Input data are generated by data_processing/02.joint_call/11.merge_sample.sh
input_path="input/fig1d_MER/"
output_path="output/fig1d_MER/"
trio_giab=GIAB_mother,GIAB_father,GIAB_son
trio_1kg=HG00512,HG00513,HG00514

[[ ! -d ${output_path} ]] && mkdir -p ${output_path}

# count Mendelian errors
# bcftools 1.15.1
bcftools view -s ${trio_giab} ${input_path}/Chinese_SV.public_samples.raw.vcf.gz | \
bcftools view -i "AC>0" | bcftools +mendelian -m c -t ${trio_giab} > ${output_path}/GIAB.raw.mendelian.txt

bcftools view -s ${trio_1kg} ${input_path}/Chinese_SV.public_samples.raw.vcf.gz | \
bcftools view -i "AC>0" | bcftools +mendelian -m c -t ${trio_1kg} > ${output_path}/1KG.raw.mendelian.txt

bcftools view -s ${trio_giab} ${input_path}/Chinese_SV.public_samples.filter.vcf.gz | \
bcftools view -i "AC>0" | bcftools +mendelian -m c -t ${trio_giab} > ${output_path}/GIAB.filter.mendelian.txt

bcftools view -s ${trio_1kg} ${input_path}/Chinese_SV.public_samples.filter.vcf.gz | \
bcftools view -i "AC>0" | bcftools +mendelian -m c -t ${trio_1kg} > ${output_path}/1KG.filter.mendelian.txt

# calcualte Mendelian error rate
ls ${output_path}/*mendelian.txt | while read result; do
    sample=$(basename $result)
    sample=${sample%.mendelian.txt}

    awk -v sample=${sample} 'FNR>1 {print sample, $2 / ($1 + $2)}' ${result}
done > ${output_path}/mendelian_summary.txt

# visualization
Rscript --vanilla -e "
library(readr)
library(dplyr)
library(ggplot2)

df_mer <- read_table('${output_path}/mendelian_summary.txt', col_names = c('name', 'mer'))
df_mer <- mutate(df_mer, 
                 group = strsplit(name, '.', fixed = TRUE) %>% sapply(function(x) x[2]),
                 group = factor(group, levels = c('raw', 'filter')))

pdf('${output_path}/fig1d_MER.pdf')
ggplot(df_mer) + geom_point(aes(group, mer)) + ylim(0, 0.1)
dev.off()
"
