library(dplyr)
library(readr)
library(IRanges)
library(ggplot2)

# read data
# the input files were generated by data_processing/03.SV_annotation/02.overlap_gwas.sh
df_gwas <- read_tsv("input/fig2cd_gwas_overlap/Chinese_SV.overlap_GWAS.10kb.bed", 
                    col_names=FALSE, na=c(".", "NA"))
df_gwas_genes <- read_tsv("input/fig2cd_gwas_overlap/GWAS_catalog_Gene.hg38.bed", 
                    col_names=FALSE, na=c(".", "NA"))

# process GWAS data
colnames(df_gwas) <- c("chr", "start", "end", "ID", "overlap_chr", "overlap_start", "overlap_end", "overlap_ID", "overlap_len")
df_gwas <- filter(df_gwas, !is.na(overlap_ID))
df_gwas$category <- gsub('.+:(.+)', '\\1', df_gwas$overlap_ID)

colnames(df_gwas_genes) <- c("chr", "start", "end", "overlap_ID")
df_gwas_genes$gene <- gsub('(.+?):.+', '\\1', df_gwas_genes$overlap_ID)
df_gwas_genes$disease <- gsub('.+?:(.+):.+', '\\1', df_gwas_genes$overlap_ID)
df_gwas_genes$category <- gsub('.+:(.+)', '\\1', df_gwas_genes$overlap_ID)

# keep only disease risk loci on autosomes, flanking them loci by 10kb
# other categories are complex traits
category_list <- c("Neurological_disorder", "Cardiovascular_disease", 
                   "Cancer", "Digestive_system_disorder",
                   "Immune_system_disorder", "Metabolic_disorder",
                   "Other_disease")

df_gwas_genes <- filter(df_gwas_genes, category %in% category_list, ! chr %in% c("chrX", "chrY")) %>%
                mutate(start = pmax(0, start - 10000), end = end + 10000)

df_gwas_genes_sum <- group_by(df_gwas_genes, chr, category) %>%
                            group_modify(~ {
                                ir <- IRanges(start = .x$start, end = .x$end)
                                reduced_ir <- reduce(ir)
                                
                                tibble(
                                start = start(reduced_ir),
                                end = end(reduced_ir),
                                disease = paste(unique(.x$disease), collapse=";")
                                )
                            }) %>% group_by(category) %>%
                            summarise(n_loci=length(start),
                                      n_disease = length(unique(unlist(strsplit(disease, ";")))),
                                      total_len=sum(end-start+1)) %>% ungroup()


# summarise GWAS SV count
df_gwas_svcount <- filter(df_gwas, category %in% category_list, ! chr %in% c("chrX", "chrY")) %>% 
    group_by(category) %>% summarise(nSV=length(unique(ID)))

df_gwas_svcount <- left_join(df_gwas_svcount, df_gwas_genes_sum, by="category")
df_gwas_svcount <- df_gwas_svcount %>% mutate(SV_per_loci = nSV/n_loci, SV_per_mb = nSV/(total_len/1e6))
df_gwas_svcount$category <- factor(df_gwas_svcount$category, levels=rev(category_list))

# visualization
if (!dir.exists("output/fig2cd_gwas_overlap")) dir.create("output/fig2cd_gwas_overlap", recursive = T)
pdf("output/fig2cd_gwas_overlap/fig2c.gwas_overlap_SV_count.pdf")
ggplot(df_gwas_svcount, aes(nSV, category)) + geom_bar(stat="identity", fill="#fbb040")
dev.off()

pdf("output/fig2cd_gwas_overlap/fig2d.gwas_overlap_loci_length.pdf")
ggplot(df_gwas_svcount, aes(total_len, category)) + geom_bar(stat="identity", fill="#fbb040")
dev.off()