library(readr)
library(dplyr)
library(tidyr)
library(boot)
library(boot.pval)
library(ggplot2)


# the input files were generated by data_processing/03.SV_annotation/01.overlap_feature.sh

df_SV <- read_tsv("input/fig2ab_feature_overlap/Chinese_SV.bed", col_names=FALSE)
colnames(df_SV) <- c("chr", "start", "end", "SVTYPE", "strand", "ID")

# summarise total length of each SV
df_SV <- df_SV %>% mutate(SVLEN = end - start) 
df_SV_summary <- df_SV %>% group_by(SVTYPE) %>%
                 summarise(SV_cov = sum(SVLEN))

# read overlap bed file
df_overlap <- read_tsv("input/fig2ab_feature_overlap/Chinese_SV.overlap_feature.bed", col_names=FALSE)
colnames(df_overlap) <- c("chr", "start", "end", "SVTYPE", "strand", "ID", "feature","feature_chr", "feature_start", "feature_end", "feature_name", "overlap")

# generate table for SV overlap with each feature
df_SV_overlap <- filter(df_overlap, feature != ".") %>% 
                 group_by(ID, feature) %>%
                 summarise(overlap = sum(overlap)) %>%
                 pivot_wider(names_from = feature, values_from = overlap, values_fill = 0)
df_SV_overlap <- left_join(df_SV, df_SV_overlap, by="ID")
df_SV_overlap[is.na(df_SV_overlap)] <- 0

# summarise overlap by SVTYPE and feature
df_overlap_summary <- filter(df_overlap, feature != ".") %>% group_by(SVTYPE, feature) %>%
                      summarise(n = length(unique(ID)), overlap = sum(overlap))

# summarise total length of each feature
annotaion_files <- read_tsv("input/fig2ab_feature_overlap/annotation_files.txt")

df_feature_summary <- tibble()
for(i in 1:nrow(annotaion_files)){
    feature_name <- annotaion_files[i, "feature"] %>% as.character()
    feature_file <- annotaion_files[i, "file"] %>% as.character()
    df_feature <- read_tsv(feature_file, col_names=FALSE)
    feature_length <- sum(df_feature[,3] - df_feature[,2])
    df_feature_summary <- bind_rows(df_feature_summary, tibble(feature = feature_name, feature_size = feature_length))
}


# merge all tables
df_overlap_merge <- left_join(df_overlap_summary, df_feature_summary, by="feature")
df_overlap_merge <- left_join(df_overlap_merge, df_SV_summary, by = "SVTYPE")

# add effective genome size as reference
# this only include non-N bases of chr1-22,X in GRCh38
df_overlap_merge$gene <- 1766089197
df_overlap_merge$genome <- 2900079631

# enrichment analysis of SVs overlap with different features
enrichment_func <- function(data, index, feature, feature_size, reference, reference_size){
    data <- data[index,]
    feature_cov <- sum(data[, feature])
    if(reference == "genome"){
        SV_cov <- sum(data$SVLEN)
    }
    else if(reference == "gene") {
        SV_cov <- sum(data$gene_all)
    }
    stat <- (feature_cov / feature_size) / (SV_cov / reference_size)
    return(stat)
}

gene_biotype <- c("protein_coding", "lncRNA", "pseudogene", "small_RNA")
function_region <- c("intergenic","exon", "intron", "UTR5", "UTR3", "PLS", "pELS", "dELS", "CTCF")
df_overlap_merge <- filter(df_overlap_merge,
                            feature %in% c(gene_biotype, function_region),
                            SVTYPE %in% c("INS", "DEL"))

# do enrichment by bootstrapping for each feature
for(i in 1:nrow(df_overlap_merge)){
    sv_type = pull(df_overlap_merge, SVTYPE)[i]
    feature = pull(df_overlap_merge, feature)[i]
    feature_size = pull(df_overlap_merge, feature_size)[i]
    if(feature %in% gene_biotype){
        ref_type = "gene"
        ref_size = pull(df_overlap_merge, gene)[i]
    }
    else if (feature %in% function_region) {
        ref_type = "genome"
        ref_size = pull(df_overlap_merge, genome)[i]
    } else {
        next()
    }

    enrich_stat <- boot(filter(df_SV_overlap, SVTYPE == sv_type), enrichment_func, R = 1000,
                        feature=feature, feature_size=feature_size, reference = ref_type, reference_size=ref_size)
    enrich_stat_ci <- boot.ci(enrich_stat, type = "perc")
    enrich_p <- boot.pval(enrich_stat, theta_null = 1)
    df_overlap_merge[i, "enrichment"] <- enrich_stat$t0
    df_overlap_merge[i, "enrichment_025"] <- enrich_stat_ci$percent[4]
    df_overlap_merge[i, "enrichment_975"] <- enrich_stat_ci$percent[5]
    df_overlap_merge[i, "p_boot"] <- enrich_p
}

feature_order <- c(gene_biotype, function_region)
df_overlap_merge <- mutate(df_overlap_merge, feature = factor(feature, levels = rev(feature_order))) %>% 
                      arrange(SVTYPE, feature)

# visualization
# Since this is done by bootstrapping, the statistics can be slightly different from those reported in Supple. Tables
if (!dir.exists("output/fig2ab_feature_overlap")) dir.create("output/fig2ab_feature_overlap", recursive = T)

pdf("output/fig2ab_feature_overlap/fig2a.genomic_reion_overlap_count.pdf")
ggplot(filter(df_overlap_merge, ! feature %in% c("protein_coding", "lncRNA", "pseudogene", "small_RNA"))) +
    geom_bar(aes(n, feature, fill=SVTYPE), stat="identity", position="dodge") +
    scale_x_log10()
dev.off()

pdf("output/fig2ab_feature_overlap/fig2a.genomic_reion_overlap_enrichment.pdf")
ggplot(filter(df_overlap_merge, ! feature %in% c("protein_coding", "lncRNA", "pseudogene", "small_RNA"))) +
    geom_point(aes(enrichment, feature, color=SVTYPE), 
               position=position_dodge(width = 0.5)) +
    geom_linerange(aes(xmin=enrichment_025, xmax=enrichment_975, y=feature, color=SVTYPE), 
                   position=position_dodge(width = 0.5)) +
    geom_vline(xintercept = 1, color = "black", linetype="dashed") +
    scale_x_log10()
dev.off()

pdf("output/fig2ab_feature_overlap/fig2b.gene_overlap_count.pdf")
ggplot(filter(df_overlap_merge, feature %in% c("protein_coding", "lncRNA", "pseudogene", "small_RNA"))) +
    geom_bar(aes(n, feature, fill=SVTYPE), stat="identity", position="dodge") +
    scale_x_log10()
dev.off()

pdf("output/fig2ab_feature_overlap/fig2b.gene_overlap_enrichment.pdf")
ggplot(filter(df_overlap_merge, feature %in% c("protein_coding", "lncRNA", "pseudogene", "small_RNA"))) +
    geom_point(aes(enrichment, feature, color=SVTYPE), 
               position=position_dodge(width = 0.5)) +
    geom_linerange(aes(xmin=enrichment_025, xmax=enrichment_975, y=feature, color=SVTYPE), 
                   position=position_dodge(width = 0.5)) +
    geom_vline(xintercept = 1, color = "black", linetype="dashed") +
    scale_x_log10()
dev.off()
