library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggridges)
library(pROC)
library(nricens)

min_max_norm <- function(x, scale = 1){
  x_min <- min(x, na.rm = T)
  x_max <- max(x, na.rm = T)
  
  return ((x - x_min) / (x_max - x_min) * scale)
}

# the input files are generated by fig3ab_prs.R and scripts described in fig3ab_prs.R's input section
df_phenotype <- read_tsv('input/fig3c-f_prs_apply/phenotype.include_mci.txt')
df_prs_beta <- read_table('output/fig3ab_prs/SNP_SV_models.txt')
df_prs_beta_condition <- read_table("output/fig3ab_prs/SNP_SV_condition_models.txt")
beta_snp <- filter(df_prs_beta, fold == 62) %>% pull(BETA_SNP)
beta_sv <- filter(df_prs_beta, fold == 62) %>% pull(BETA_SV)
beta_snp_condition <- filter(df_prs_beta_condition, fold == 62) %>% pull(BETA_SNP)
beta_sv_condition <- filter(df_prs_beta_condition, fold == 62) %>% pull(BETA_SV)

df_prs_snp <- read_table("input/fig3c-f_prs_apply/fold62.include_mci.SNP.sscore")
df_prs_snp_condition <- read_table("input/fig3c-f_prs_apply/fold62.include_mci.SNP_condition.sscore")
df_prs_sv <- read_table("input/fig3c-f_prs_apply/fold62.include_mci.SV.sscore")

df_prs <- inner_join(select(df_prs_snp, IID, score_snp=SCORE), 
                     select(df_prs_snp_condition, IID, score_snp_condition=SCORE))
df_prs <- inner_join(df_prs, select(df_prs_sv, IID, score_sv=SCORE))

df_prs <- mutate(df_prs, 
                score = (beta_snp * score_snp + beta_sv * score_sv),
                score_condition = (beta_snp_condition * score_snp_condition + beta_sv_condition * score_sv))

# merge with phenotype
df_prs_merge <- inner_join(df_prs, df_phenotype, by="IID")

# min-max normalization for visualization
df_prs_merge <- mutate(df_prs_merge,
                       score_snp_norm = min_max_norm(score_snp),
                       score_snp_condition_norm = min_max_norm(score_snp_condition),
                       score_sv_norm = min_max_norm(score_sv),
                       score_norm = min_max_norm(score),
                       score_condition_norm = min_max_norm(score_condition),
                       score_level = cut(score_norm, breaks=quantile(score_norm, probs=seq(0,1,1/3)), labels=c("Low", "Medium", "High"), include.lowest=TRUE))

# visualization
if (!dir.exists("output/fig3c-f_prs_apply")) dir.create("output/fig3c-f_prs_apply", recursive = T)
# PRS correlation plots
pdf("output/fig3c-f_prs_apply/fig3c.prs_correlation.pdf")
ggplot(df_prs_merge, aes(score_snp_norm, score_sv_norm)) + 
    geom_point() + geom_smooth(method="lm", color="red")
dev.off()

pdf("output/fig3c-f_prs_apply/extended_fig3c.conditional_prs_correlation.pdf")
ggplot(df_prs_merge, aes(score_norm, score_condition_norm)) + 
    geom_point() + geom_smooth(method="lm", color="red")
dev.off()

# PRS density plot
score_norm_tertile_breaks <- quantile(filter(df_prs_merge, !is.na(Diagnosis))$score_norm, probs=seq(0,1,1/3))
pdf("output/fig3c-f_prs_apply/fig3d.prs_distribution.pdf", width=4, height=2.5)
ggplot(filter(df_prs_merge, !is.na(Diagnosis))) + 
    geom_density_ridges_gradient(aes(score_norm, Diagnosis, fill=..x..), lwd=0.2) +
    scale_fill_gradient(low = "white", high = "red") +
    scale_x_continuous(limits=c(0,1), expand = c(0, 0)) + 
    scale_y_discrete(expand = c(0, 0), limits = c("NC", "MCI", "AD")) +
    geom_vline(xintercept = score_norm_tertile_breaks[2], color = "black", lwd = 0.2, linetype="dashed") +
    geom_vline(xintercept = score_norm_tertile_breaks[3], color = "black", lwd = 0.2, linetype="dashed") +
    theme_ridges(grid = FALSE) +
    theme(text = element_text(size = 10, color = "black", face="plain"),
          axis.line.x = element_line(linewidth = 0.2), axis.ticks = element_line(linewidth = 0.2),
          rect = element_rect(fill = "transparent"), axis.title = element_blank())
dev.off()


# proportion by tertiles
df_prop_by_tertile <- filter(df_prs_merge, !is.na(Diagnosis), !is.na(score_norm)) %>% group_by(score_level) %>%
                    summarise(NC = mean(Diagnosis == "NC"), 
                              MCI = mean(Diagnosis == "MCI"),
                              AD = mean(Diagnosis == "AD")) %>%
                    pivot_longer(-score_level, names_to = "Diagnosis", values_to = "proportion")

pdf("output/fig3c-f_prs_apply/fig3e.diagnosis_by_prs_group.pdf")
ggplot(df_prop_by_tertile, aes(score_level, proportion, fill=Diagnosis)) +
    geom_bar(position="stack", stat="identity") +
    scale_fill_manual(values=c("#ed1f24", "#f9a043", "#6799d1"))
dev.off()

# MCI vs NC analysis
roc_snp <- roc(factor(Diagnosis, levels=c("NC","MCI")) ~ score_snp, data=filter(df_prs_merge, Diagnosis %in% c("NC","MCI")))
roc_sv <- roc(factor(Diagnosis, levels=c("NC","MCI")) ~ score_sv, data=filter(df_prs_merge, Diagnosis %in% c("NC","MCI")))
roc_merge <- roc(factor(Diagnosis, levels=c("NC","MCI")) ~ score, data=filter(df_prs_merge, Diagnosis %in% c("NC","MCI")))

df_prs_merge_mci_nc <- filter(df_prs_merge, Diagnosis %in% c("NC","MCI")) %>%
                    mutate(MCI = if_else(Diagnosis == "MCI", 1, 0))
fit_snp <- glm(MCI ~ score_snp, data = df_prs_merge_mci_nc, family="binomial", x = TRUE, y = TRUE)
fit_sv <- glm(MCI ~ score_sv, data = df_prs_merge_mci_nc, family="binomial", x = TRUE, y = TRUE)
fit_merge <- glm(MCI ~ score, data = df_prs_merge_mci_nc, family="binomial", x = TRUE, y = TRUE)

nri_sv_snp <- nribin(mdl.std = fit_snp, mdl.new = fit_sv, cut = 0.05, updown = "diff", niter = 0)
nri_merge_snp <- nribin(mdl.std = fit_snp, mdl.new = fit_merge, cut = 0.05, updown = "diff", niter = 0)
nri_merge_sv <- nribin(mdl.std = fit_sv, mdl.new = fit_merge, cut = 0.05, updown = "diff", niter = 0)

# ROC curves
pdf("output/fig3c-f_prs_apply/fig3f.roc.pdf")
ggroc(list(SNP=roc_snp, SV=roc_sv, 'SNP+SV'=roc_merge), legacy.axes = TRUE)
dev.off()

# ROC statistics
cat("####### Statistics of MCI vs NC #######\n")
cat("# AUC (95% CI)\n")
cat("SNP: ", roc_snp$auc, " (", ci(roc_snp)[1], "-", ci(roc_snp)[3], ")\n")
cat("SV: ", roc_sv$auc, " (", ci(roc_sv)[1], "-", ci(roc_sv)[3], ")\n")
cat("SNP+SV: ", roc_merge$auc, " (", ci(roc_merge)[1], "-", ci(roc_merge)[3], ")\n")

cat("# DeLong test\n")
cat("SV vs SNP: ", roc.test(roc_snp, roc_sv, method = "delong")$p.value, "\n")
cat("SNP+SV vs SNP: ", roc.test(roc_snp, roc_merge, method = "delong")$p.value, "\n")
cat("SNP+SV vs SV: ", roc.test(roc_sv, roc_merge, method = "delong")$p.value, "\n")

cat("# NRI \n")
cat("SV vs SNP: ", nri_sv_snp$nri['NRI',], "\n")
cat("SNP+SV vs SNP: ", nri_merge_snp$nri['NRI',], "\n")
cat("SNP+SV vs SV: ", nri_merge_sv$nri['NRI',], "\n")
