library(dplyr)
library(readr)
library(pROC)
library(rcompanion)
library(ggplot2)

# The PRS scores were generated by 06.score.sh, 07.score_SNP_SV.sh, 08.score_SNP_SV_condition.sh under data_processing/05.PRS/

df_phenotype <- read_tsv("input/fig3ab_prs/phenotype.txt")

# PRS statistics function
get_PRS_stat <- function(df_merge, phenotype, covar_adjust=" Age + Sex + PC1 + PC2 + PC3"){
	regression_full <- paste0(phenotype, " ~ SCORE + ", covar_adjust)
	regression_null <- paste0(phenotype, " ~ ", covar_adjust)
	# logistic regression
	fit_full <- glm(regression_full, data=df_merge, family="binomial")
	fit_null <- glm(regression_null, data=df_merge, family="binomial")
    # r2 increase from null
	r2_full <- nagelkerke(fit_full)$Pseudo.R.squared.for.model.vs.null[3]
	r2_PRS <- nagelkerke(fit_full, fit_null)$Pseudo.R.squared.for.model.vs.null[3]
	# get beta, se, P
	coef_full <- summary(fit_full)$coef["SCORE",]
	beta_full <- coef_full[1]
	se_full <- coef_full[2]
	p_full <- coef_full[4]
	return(data.frame(BETA=beta_full, SE=se_full, P=p_full, r2_PRS=r2_PRS, r2_full=r2_full))
}


pheno <- "AD"
score_files_snp_sv_condition <- list.files("input/fig3ab_prs/snp_sv_condition/", full.names=TRUE)
if (!dir.exists("output/fig3ab_prs")) dir.create("output/fig3ab_prs", recursive = T)
################ SNP models ###############
# parse score files
score_files_snp <- list.files("input/fig3ab_prs/snp/", full.names=TRUE)
df_summary_snp <- tibble(file=score_files_snp)
df_summary_snp$PRS_type <- gsub(".+fold(\\d+)\\.(\\w+?)\\.(.+)\\.sscore", "\\2", score_files_snp)
df_summary_snp$threshold <- gsub(".+fold(\\d+)\\.(\\w+?)\\.(.+)\\.sscore", "\\3", score_files_snp) %>% as.numeric()
df_summary_snp$fold <- gsub(".+fold(\\d+)\\.(\\w+?)\\.(.+)\\.sscore", "\\1", score_files_snp) %>% as.numeric()

# summarise all PRS results
# df_score_all <- tibble()
for (i in 1:nrow(df_summary_snp)) {
	df_score <- read_table(df_summary_snp$file[i], col_names = TRUE, col_types = cols())
	df_merge <- inner_join(df_score, df_phenotype, by = "IID")
    df_merge[, pheno] <- df_merge[, pheno] - 1
	df_stat <- get_PRS_stat(filter(df_merge), phenotype = pheno)	

	df_summary_snp[i, 'Count'] <- mean(df_score$Count)
	df_summary_snp[i, 6:10] <- df_stat
	df_summary_snp[i, "AUC"] <- roc(get(pheno) ~ SCORE, data=df_merge, direction="<", levels = c(0,1))$auc %>% as.numeric
}

write_tsv(df_summary_snp, 'output/fig3ab_prs/SNP_models.txt')

################ SV models ###############
# parse score files
score_files_sv <- list.files("input/fig3ab_prs/sv/", full.names=TRUE)
df_summary_sv <- tibble(file=score_files_sv)
df_summary_sv$PRS_type <- gsub(".+fold(\\d+)\\.(\\w+?)\\.(.+)\\.sscore", "\\2", score_files_sv)
df_summary_sv$threshold <- gsub(".+fold(\\d+)\\.(\\w+?)\\.(.+)\\.sscore", "\\3", score_files_sv) %>% as.numeric()
df_summary_sv$fold <- gsub(".+fold(\\d+)\\.(\\w+?)\\.(.+)\\.sscore", "\\1", score_files_sv) %>% as.numeric()

# summarise all PRS results
# df_score_all <- tibble()
for (i in 1:nrow(df_summary_sv)) {
	df_score <- read_table(df_summary_sv$file[i], col_names = TRUE, col_types = cols())
	df_merge <- inner_join(df_score, df_phenotype, by = "IID")
    df_merge[, pheno] <- df_merge[, pheno] - 1
	df_stat <- get_PRS_stat(filter(df_merge), phenotype = pheno)	

	df_summary_sv[i, 'Count'] <- mean(df_score$Count)
	df_summary_sv[i, 6:10] <- df_stat
	df_summary_sv[i, "AUC"] <- roc(get(pheno) ~ SCORE, data=df_merge, direction="<", levels = c(0,1))$auc %>% as.numeric
}

write_tsv(df_summary_sv, 'output/fig3ab_prs/SV_models.txt')

################ SNP + SV model ###############
score_files_snp_sv <- list.files("input/fig3ab_prs/snp_sv/", full.names=TRUE)
df_score_file_snp_sv <- tibble(file=score_files_snp_sv)
df_score_file_snp_sv$fold <- gsub(".+fold(\\d+)\\.(\\w+?)\\.score.+", "\\1", score_files_snp_sv) %>% as.numeric()
df_score_file_snp_sv$PRS_type <- gsub(".+fold(\\d+)\\.(\\w+?)\\.score.+", "\\2", score_files_snp_sv)

df_summary_snp_sv <- tibble()
for (i in unique(df_score_file_snp_sv$fold)) {
	file_snp <- filter(df_score_file_snp_sv, fold==i, PRS_type=="SNP")$file
	file_sv <- filter(df_score_file_snp_sv, fold==i, PRS_type=="SV")$file
	score_snp <- read_table(file_snp, col_names = TRUE, col_types = cols())
	score_sv <- read_table(file_sv, col_names = TRUE, col_types = cols())

	df_merge <- inner_join(select(score_snp, IID, SCORE_SNP=SCORE), 
						   select(score_sv, IID, SCORE_SV=SCORE), by = "IID")
	df_merge <- inner_join(df_merge, df_phenotype, by = "IID")
	df_merge[,pheno] <- df_merge[,pheno] - 1

    # fit logistic regression on original score
	regression_raw <- paste0(pheno, " ~ SCORE_SNP + SCORE_SV + Age + Sex + PC1 + PC2 + PC3")
	fit_raw <- glm(regression_raw, data = df_merge, family = "binomial")

    # extract beta
	BETA_SNP=summary(fit_raw)$coefficients["SCORE_SNP",1]
	BETA_SV=summary(fit_raw)$coefficients["SCORE_SV",1]

    # calcualte SNP+SV PRS, here we used the absolute value of beta to penalize models with negative beta
    # however, given all models have positive beta, this is equivalent to just using beta
	df_merge$SCORE_MERGE <- df_merge$SCORE_SNP * abs(BETA_SNP) + df_merge$SCORE_SV * abs(BETA_SV)
    
    # fit logistic regression on SNP + SV scores
	regression_full <- paste0(pheno, " ~ SCORE_MERGE + Age + Sex + PC1 + PC2 + PC3")
	regression_null <- paste0(pheno, " ~ Age + Sex + PC1 + PC2 + PC3")
	fit_full <- glm(regression_full, data = df_merge, family = "binomial")
	fit_null <- glm(regression_null, data = df_merge, family = "binomial")
    # calculate r2 and AUC
	r2_full <- nagelkerke(fit_full)$Pseudo.R.squared.for.model.vs.null[3]
	r2_PRS <- nagelkerke(fit_full, fit_null)$Pseudo.R.squared.for.model.vs.null[3]
	fit_auc <- roc(get(pheno) ~ SCORE_MERGE, data=df_merge, direction="<", levels = c(0,1))$auc %>% as.numeric()
    # summarise statistics
	df_stat <- tibble(fold=i, 
					  Count=mean(score_snp$Count) + mean(score_sv$Count),
					  r2_PRS=r2_PRS, 
					  r2_full=r2_full, 
					  AUC=fit_auc,
					  BETA_SNP=BETA_SNP, 
					  BETA_SV=BETA_SV)

	df_summary_snp_sv <- bind_rows(df_summary_snp_sv, df_stat)
}

write_tsv(df_summary_snp_sv, 'output/fig3ab_prs/SNP_SV_models.txt')

################ SNPadj + SV model ###############
df_score_file_snp_sv_condition <- tibble(file=score_files_snp_sv_condition)
df_score_file_snp_sv_condition$fold <- gsub(".+fold(\\d+)\\.(\\w+?)\\.score.+", "\\1", score_files_snp_sv_condition) %>% as.numeric()
df_score_file_snp_sv_condition$PRS_type <- gsub(".+fold(\\d+)\\.(\\w+?)\\.score.+", "\\2", score_files_snp_sv_condition)

df_summary_snp_sv_condition <- tibble()
for (i in unique(df_score_file_snp_sv_condition$fold)) {
	file_snp <- filter(df_score_file_snp_sv_condition, fold==i, PRS_type=="SNP")$file
	file_sv <- filter(df_score_file_snp_sv_condition, fold==i, PRS_type=="SV")$file
	score_snp <- read_table(file_snp, col_names = TRUE, col_types = cols())
	score_sv <- read_table(file_sv, col_names = TRUE, col_types = cols())

	df_merge <- inner_join(select(score_snp, IID, SCORE_SNP=SCORE), 
						   select(score_sv, IID, SCORE_SV=SCORE), by = "IID")
	df_merge <- inner_join(df_merge, df_phenotype, by = "IID")
	df_merge[,pheno] <- df_merge[,pheno] - 1

    # fit logistic regression on original score
	regression_raw <- paste0(pheno, " ~ SCORE_SNP + SCORE_SV + Age + Sex + PC1 + PC2 + PC3")
	fit_raw <- glm(regression_raw, data = df_merge, family = "binomial")

    # extract beta
	BETA_SNP=summary(fit_raw)$coefficients["SCORE_SNP",1]
	BETA_SV=summary(fit_raw)$coefficients["SCORE_SV",1]

    # calcualte SNP+SV PRS, here we used the absolute value of beta to penalize models with negative beta
    # however, given all models have positive beta, this is equivalent to just using beta
	df_merge$SCORE_MERGE <- df_merge$SCORE_SNP * abs(BETA_SNP) + df_merge$SCORE_SV * abs(BETA_SV)
    
    # fit logistic regression on SNP + SV scores
	regression_full <- paste0(pheno, " ~ SCORE_MERGE + Age + Sex + PC1 + PC2 + PC3")
	regression_null <- paste0(pheno, " ~ Age + Sex + PC1 + PC2 + PC3")
	fit_full <- glm(regression_full, data = df_merge, family = "binomial")
	fit_null <- glm(regression_null, data = df_merge, family = "binomial")
    # calculate r2 and AUC
	r2_full <- nagelkerke(fit_full)$Pseudo.R.squared.for.model.vs.null[3]
	r2_PRS <- nagelkerke(fit_full, fit_null)$Pseudo.R.squared.for.model.vs.null[3]
	fit_auc <- roc(get(pheno) ~ SCORE_MERGE, data=df_merge, direction="<", levels = c(0,1))$auc %>% as.numeric()
    # summarise statistics
	df_stat <- tibble(fold=i, 
					  Count=mean(score_snp$Count) + mean(score_sv$Count),
					  r2_PRS=r2_PRS, 
					  r2_full=r2_full, 
					  AUC=fit_auc,
					  BETA_SNP=BETA_SNP, 
					  BETA_SV=BETA_SV)

	df_summary_snp_sv_condition <- bind_rows(df_summary_snp_sv_condition, df_stat)
}

write_tsv(df_summary_snp_sv_condition, 'output/fig3ab_prs/SNP_SV_condition_models.txt')

# visualization
df_plot <- bind_rows(filter(df_summary_snp, threshold == 0.01) %>% select(PRS_type, r2_PRS, AUC),
                     filter(df_summary_sv, threshold == 0.05) %>% select(PRS_type, r2_PRS, AUC),
                     mutate(df_summary_snp_sv, PRS_type="SNP+SV") %>% select(PRS_type, r2_PRS, AUC),
                     mutate(df_summary_snp_sv_condition, PRS_type="SNPadj+SV") %>% select(PRS_type, r2_PRS, AUC))
df_plot <- mutate(df_plot, PRS_type = factor(PRS_type, levels=c("SNP", "SV", "SNP+SV", "SNPadj+SV")))

pdf("output/fig3ab_prs/fig3a_prs_r2.pdf")
ggplot(filter(df_plot, PRS_type!="SNPadj+SV"), aes(PRS_type, r2_PRS, color=PRS_type)) + 
    geom_boxplot(outlier.shape = NA, color="black") + 
    geom_jitter(position=position_jitter(0.2))
dev.off()

pdf("output/fig3ab_prs/fig3b_prs_auc.pdf")
ggplot(filter(df_plot, PRS_type!="SNPadj+SV"), aes(PRS_type, AUC, color=PRS_type)) + 
    geom_boxplot(outlier.shape = NA, color="black") + 
    geom_jitter(position=position_jitter(0.2))
dev.off()

pdf("output/fig3ab_prs/extended_fig3a_prs_condition_r2.pdf")
ggplot(filter(df_plot, PRS_type %in% c("SNP+SV", "SNPadj+SV")), aes(PRS_type, r2_PRS, color=PRS_type)) +
    geom_boxplot(outlier.shape = NA, color="black") +
    geom_jitter(position=position_jitter(0.2))
dev.off()

pdf("output/fig3ab_prs/extended_fig3b_prs_condition_auc.pdf")
ggplot(filter(df_plot, PRS_type %in% c("SNP+SV", "SNPadj+SV")), aes(PRS_type, AUC, color=PRS_type)) +
    geom_boxplot(outlier.shape = NA, color="black") +
    geom_jitter(position=position_jitter(0.2))
dev.off()

# This reproduce Supplementary Table 10
cat("####### Supplementary Table 10 #######\n")
# counts are allele counts here, we need to divide by 2 to get variant counts
df_summary_snp %>% group_by(PRS_type, threshold) %>% 
    summarise(r2_PRS_mean=mean(r2_PRS, na.rm=TRUE),
              beta=mean(BETA, na.rm=TRUE), 
              count=mean(Count/2, na.rm=TRUE), 
              AUC_mean=mean(AUC, na.rm=TRUE)) %>% 
    ungroup() %>% print()

df_summary_sv %>% group_by(PRS_type, threshold) %>% 
    summarise(r2_PRS_mean=mean(r2_PRS, na.rm=TRUE),
              beta=mean(BETA, na.rm=TRUE), 
              count=mean(Count/2, na.rm=TRUE), 
              AUC_mean=mean(AUC, na.rm=TRUE)) %>% 
    ungroup() %>% print()
