#!/bin/bash


# This script reproduce all locuszoom plots in the paper:
# Fig. 4c, Extended Data Fig. 4, Extended Data Fig. 6

# summary statistics are generated by:
# AD assocaition: 04.association_plink.sh, 05.association_regenie.sh under data_processing/06.candidate_locus
# Blood eQTL: 04.association_plink.sh under data_processing/06.candidate_locus
# Brain bulk eQTL: 10.1038/s41588-023-01300-6, 10.1038/s41588-024-02057-2
# Brain snRNA eQTL: fig5c-d_snrna_analysis.R

# Note:
# Since the TR is too polymorphic, it generally has low LD with nearby SNPs
# So we use |r| for plot to increase the resolution for low LD SNPs
# The LD files still have rsqaure header to fit the requirement of locuszoom

[[ ! -d "output/fig4c_locuszoom/" ]] && mkdir -p "output/fig4c_locuszoom/"

# Fig. 4c AD associaiton in Hong Kong Chinese
locuszoom --epacts input/fig4c_locuszoom/HK.AD.txt.gz \
--refsnp 5:177554490_C_CCCG \
--chr 5 \
--start 177322587 \
--end 177754013 \
--ld  input/fig4c_locuszoom/HK.r.ld \
--build hg38 \
--plotonly \
-p $(pwd)/output/fig4c_locuszoom/fig4c.HK.AD ymax=10 signifLine=7.3 signifLineColor=red height=5 width=8 LDTitle="|r|"

# Extended Data Fig. 6 Blood eQTL
locuszoom --epacts input/fig4c_locuszoom/HK.Blood_bulk_eQTL.txt.gz \
--refsnp 5:177554490_C_CCCG \
--chr 5 \
--start 177322587 \
--end 177754013 \
--ld  input/fig4c_locuszoom/HK.r.ld \
--build hg38 \
--plotonly \
-p $(pwd)/output/fig4c_locuszoom/extended_fig6.HK.Blood_bulk_eQTL ymax=35 signifLine=7.3 signifLineColor=red height=5 width=8 LDTitle="|r|"

# Extended Data Fig. 4a AD association in European
# AD (Bonferroni-corrected p-value cutoff: 5.98e-05)
# LD by CCG19+ to show the LD with the risk allele for LD analysis
locuszoom --epacts input/fig4c_locuszoom/EUR.AD.txt.gz \
--refsnp 5:177554490_C_CCCG19 \
--chr 5 \
--start 177322587 \
--end 177754013 \
--ld  input/fig4c_locuszoom/EUR.CCG19_r.ld \
--build hg38 \
--plotonly \
-p $(pwd)/output/fig4c_locuszoom/extended_fig4a.EUR.AD ymax=8 signifLine=4.2 signifLineColor=red height=5 width=8 LDTitle="|r|"

# Extended Data Fig. 6 Brain bulk eQTL (ROSMAP)
locuszoom --epacts input/fig4c_locuszoom/EUR.Brain_bulk_eQTL.txt.gz \
--refsnp 5:177554490_C_CCCG \
--chr 5 \
--start 177322587 \
--end 177754013 \
--ld  input/fig4c_locuszoom/EUR.r.ld \
--build hg38 \
--plotonly \
-p $(pwd)/output/fig4c_locuszoom/extended_fig6.EUR.Brain_bulk_eQTL ymax=40 signifLine=7.3 signifLineColor=red height=5 width=8 LDTitle="|r|"

# Extended Data Fig. 6  Neuron eQTL
locuszoom --epacts input/fig4c_locuszoom/EUR.Brain_snRNA.neuron.txt.gz \
--refsnp 5:177554490_C_CCCG \
--chr 5 \
--start 177322587 \
--end 177754013 \
--ld  input/fig4c_locuszoom/EUR.r.ld \
--build hg38 \
--plotonly \
-p $(pwd)/output/fig4c_locuszoom/extended_fig6.EUR.Brain_snRNA.neuron ymax=25 signifLine=7.3 signifLineColor=red height=5 width=8 LDTitle="|r|"
