library(readr)
library(dplyr)
library(ggplot2)

# these input files are generated by fig5c-d_snrna_analysis.R
df_deg_ad <- read_tsv('input/fig6b_deg_correlation/AD_DEG.txt')
df_deg_ccg <- read_tsv('input/fig6a_deg_count/FAM193B_CCG_deg_in_NC.txt')

# merge tables
df_deg_merge <- inner_join(select(df_deg_ad, primerid, beta_ad = coef),
                           filter(df_deg_ccg, celltype == 'neuron') %>% select(primerid, beta_ccg = coef)) %>%
                filter(!is.na(beta_ad), !is.na(beta_ccg))

# this is used to plot Fig. 6b
if(! dir.exists("output/fig6b_deg_correlation")) dir.create("output/fig6b_deg_correlation", recursive = T)
pdf("output/fig6b_deg_correlation/fig6b.deg_correlation.pdf")
ggplot(df_deg_merge, aes(beta_ad, beta_ccg)) +
    geom_point() + geom_smooth(method='lm') +
    xlim(-0.5, 0.5) + ylim(-0.1, 0.1)
dev.off()

# report statistics
cat("######## Statistical results ########\n")
result <- cor.test(df_deg_merge$beta_ad, df_deg_merge$beta_ccg)
cat("r: ", result$estimate, "\n")
cat("P: ", result$p.value, "\n")
