library(readr)
library(dplyr)
library(ggplot2)

# this is generated by fig5c-d_snrna_analysis.R
df_deg <- read_tsv('input/fig6a_deg_count/FAM193B_CCG_deg_in_NC.txt')

# reproduce source data of Fig. 6a
df_deg_count <- filter(df_deg, FDR < 0.05, !is.na(coef)) %>% 
            mutate(group = if_else(coef > 0, "up", "down")) %>%
            group_by(celltype, group) %>%
            summarise(n=n())
df_deg_count <- mutate(df_deg_count,
                       celltype = factor(celltype, levels = c("mic", "OPC", "oligo", "astro", "neuron")),
                       group = factor(group, levels = c("up", "down")))

if (!dir.exists("output/fig6a_deg_count")) dir.create("output/fig6a_deg_count", recursive = T)
pdf("output/fig6a_deg_count/fig6a.deg_count.pdf")
ggplot(df_deg_count, aes(n, celltype, fill=group)) + 
    geom_bar(stat="identity", color="black")
dev.off()