library(clusterProfiler)
library(org.Hs.eg.db)
library(readr)
library(dplyr)
library(ggplot2)

# This script has been run with packages versions:
# org.Hs.eg.db==3.17.0 
# clusterProfiler==4.8.2

# this is generated by fig5c-d_snrna_analysis.R
df_deg <- read_tsv('input/fig6a_deg_count/FAM193B_CCG_deg_in_NC.txt')
df_deg <- filter(df_deg, celltype == "neuron")

# GO enrichment
# Since enrichGO is nondeterministic,
# the statsitics may not be the same as in the manuscript
go_up <- filter(df_deg, FDR < 0.05, coef > 0)$primerid %>%
  enrichGO(org.Hs.eg.db, keyType = "SYMBOL", ont = "BP",
           pvalueCutoff = 0.1, qvalueCutoff=0.1, readable = TRUE)
go_down <- filter(df_deg, FDR < 0.05, coef < 0)$primerid %>%
  enrichGO(org.Hs.eg.db, keyType = "SYMBOL", ont = "BP",
           pvalueCutoff = 0.1, qvalueCutoff=0.1, readable = TRUE)

df_go_up <- as_tibble(go_up) %>% mutate(group="up")
df_go_down <- as_tibble(go_down)  %>% mutate(group="down")


up_go <- c("cytoplasmic translation",
           "macroautophagy",
           "neuron death",
           "response to endoplasmic reticulum stress",
           "neuron apoptotic process")
down_go <- c("cytosolic transport",
             "synapse organization",
             "chromatin remodeling",
             "regulation of DNA repair")

df_plot <- bind_rows(
  filter(df_go_up, Description %in% up_go),
  filter(df_go_down, Description %in% down_go)
)

df_plot <- mutate(df_plot, 
                  group = factor(group, levels=c("up", "down")),
                  Description = factor(Description, levels=rev(c(up_go, down_go))))

if (!dir.exists("output/fig6c_go")) dir.create("output/fig6c_go", recursive = T)
pdf("output/fig6c_go/fig6c_go.pdf")
ggplot(df_plot, aes(-log10(qvalue), Description, fill = group)) +
  geom_bar(stat = "identity", color="black")
dev.off()

