library(org.Hs.eg.db)
library(msigdbr)
library(clusterProfiler)
library(enrichplot)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)

# This script has been run with packages versions:
# org.Hs.eg.db==3.18.0
# msigdbr==25.1.1
# clusterProfiler==4.8.1

# these input files are generated by data_processing/06.candidate_locus/06.IMR32_DEG.R
df_rsem_gene_cpm <- read_tsv("input/fig6g-i_imr32_rnaseq/gene_expression_matrix_cpm.txt")
df_resLFC <- read_tsv("input/fig6g-i_imr32_rnaseq/DEG_result_lfcShrink.txt")

# Heatmap of significant DEGs
df_heatmap_plot <- filter(df_rsem_gene_cpm, Gene %in% filter(df_resLFC, padj < 0.05)$Gene)
# rowwise normalize cpm to Z score for visualization
df_heatmap_plot <- select(df_heatmap_plot, OE_1:PC_6) %>% as.matrix() %>%
                t() %>% scale() %>% t() %>% as_tibble() %>%
                mutate(Gene = df_heatmap_plot$Gene)
# pivot wide to long table
df_heatmap_plot_long <- pivot_longer(df_heatmap_plot, OE_1:PC_6, 
                                     names_to = "sample", values_to = "cpm")
# join with statistics
df_heatmap_plot_long <- left_join(df_heatmap_plot_long, 
                                  select(df_resLFC, Gene, log2FoldChange, pvalue),
                                  by = "Gene")
# sort by log2FC for visualization
df_heatmap_plot_long <- arrange(df_heatmap_plot_long, log2FoldChange) %>%
                    mutate(sample = factor(sample, levels = c("PC_1", "PC_2", "PC_3", "PC_4", "PC_5", "PC_6",
                                                              "OE_1", "OE_2", "OE_3", "OE_4", "OE_5", "OE_6")),
                           Gene = factor(Gene, levels = unique(Gene)))

if (! dir.exists("output/fig6g-i_imr32_rnaseq")) dir.create("output/fig6g-i_imr32_rnaseq", recursive = T)

# Fig.6g Heatmap
pdf("output/fig6g-i_imr32_rnaseq/fig6g.heatmap_DEG.pdf", height = 2.3, width = 3)
ggplot(df_heatmap_plot_long, aes(sample, Gene, fill = cpm)) + 
    geom_tile() +
    scale_fill_gradient2(low = "#2E5C9E", mid = "white", high = "#D73027") +
    theme(axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.title = element_blank(), 
          panel.background = element_blank(), axis.ticks = element_blank())
dev.off()

# Fig.6h GO
go_up <- filter(df_resLFC, padj < 0.05, log2FoldChange > 0, !is.na(Symbol))$Gene %>%
        enrichGO(OrgDb = "org.Hs.eg.db", keyType = "ENSEMBL", ont = "BP", readable = TRUE)
go_down <- filter(df_resLFC, padj < 0.05, log2FoldChange < 0, !is.na(Symbol))$Gene %>%
        enrichGO(OrgDb = "org.Hs.eg.db", keyType = "ENSEMBL", ont = "BP", readable = TRUE)

df_go_plot <- bind_rows(as_tibble(go_up) %>% filter(ID %in% c("GO:0006119",
                                                              "GO:0022904",
                                                              "GO:0046578")),
                        as_tibble(go_down) %>% filter(ID %in% c("GO:0043620",
                                                                "GO:0034620",
                                                                "GO:0140467")))
df_go_plot$group <- rep(c("up", "down"), each = 3)
df_go_plot$group <- factor(df_go_plot$group, levels = c("up", "down"))
df_go_plot$Description <- factor(df_go_plot$Description, levels = rev(df_go_plot$Description))

pdf("output/fig6g-i_imr32_rnaseq/fig6h.GO.pdf")
ggplot(df_go_plot, aes(-log10(qvalue), Description, fill = group)) + geom_bar(stat = "identity")
dev.off()

# Fig.6i GSEA
C2_t2g <- msigdbr(species = "Homo sapiens", collection = "C2") %>% 
  dplyr::select(gs_name, db_gene_symbol)

# exclude FAM193B and rank by beta / se
df_res_gsea <- filter(df_resLFC, Symbol != "FAM193B", !is.na(Symbol)) %>%
           mutate(z = log2FoldChange / lfcSE) %>%
           dplyr::arrange(desc(z))
gene_list <- df_res_gsea$z
names(gene_list) <- df_res_gsea$Symbol

# run GSEA
c2_gsea <- GSEA(gene_list, TERM2GENE = C2_t2g, pvalueCutoff = 0.2)

# plot
pdf("output/fig6g-i_imr32_rnaseq/fig6i.GSEA.pdf", height = 2.3, width = 3)
gseaplot2(c2_gsea, 
          geneSetID = c('REACTOME_G1_S_DNA_DAMAGE_CHECKPOINTS', 
                        'REACTOME_REGULATION_OF_APOPTOSIS'),
          subplots = 1:2)
dev.off()
